services:
  model-service:
    build: ./clip_service
    container_name: clip-model-service
    env_file: .env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:8000/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 20
      start_period: 200s

  video-processor:
    build: ./video_processor
    container_name: video-preprocessor
    env_file: .env
    depends_on:
      model-service:
        condition: service_healthy
    command: python main.py

  annotation-service:
    build: ./annotation_service
    container_name: annotation-service
    env_file: .env
    depends_on:
      video-processor:
        condition: service_started
    command: python annotation_service.py

  db-saver:
    build: ./db_saver
    container_name: db-saver
    env_file: .env
    depends_on:
      annotation-service:
        condition: service_started
    command: python db_saver.py
